name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: [self-hosted, jslaime-01]
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "Learning Lab User"
